[
  {
    Type: System.Exception,
    Value: Inner message2,
    Mechanism: {
      Type: chained,
      Source: InnerExceptions[1],
      Synthetic: false,
      IsExceptionGroup: false,
      ExceptionId: 2,
      ParentId: 0,
      Data: {
        HResult: 0x80131500
      }
    }
  },
  {
    Type: System.Exception,
    Value: Inner message1,
    Mechanism: {
      Type: chained,
      Source: InnerExceptions[0],
      Synthetic: false,
      IsExceptionGroup: false,
      ExceptionId: 1,
      ParentId: 0,
      Data: {
        HResult: 0x80131500
      }
    }
  },
  {
    Type: System.AggregateException,
    Value: One or more errors occurred.,
    Mechanism: {
      Type: AppDomain.UnhandledException,
      Handled: false,
      Synthetic: false,
      IsExceptionGroup: true,
      ExceptionId: 0,
      Data: {
        foo: bar,
        HResult: 0x80131500
      }
    }
  }
]